In [7]:
import pandas as pd
melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
melb_df = melb_data.copy()
# создаём пустой список
unique_list = []
# пробегаемся по именам столбцов в таблице
for col in melb_df.columns:
    # создаём кортеж (имя столбца, число уникальных значений)
    item = (col, melb_df[col].nunique(),melb_df[col].dtype) 
    # добавляем кортеж в список
    unique_list.append(item) 
# создаём вспомогательную таблицу и сортируем её
unique_counts = pd.DataFrame(
    unique_list,
    columns=['Column_Name', 'Num_Unique', 'Type']
).sort_values(by='Num_Unique',  ignore_index=True)
# выводим её на экран
display(unique_counts)

      Column_Name  Num_Unique     Type
0            Type           3   object
1          Method           5   object
2      Regionname           8   object
3           Rooms           9    int64
4        Bathroom           9    int64
5             Car          11    int64
6         Bedroom          12    int64
7     CouncilArea          33   object
8            Date          58   object
9       YearBuilt         144    int64
10       Postcode         198    int64
11       Distance         202  float64
12        SellerG         268   object
13  Propertycount         311    int64
14         Suburb         314   object
15   BuildingArea         602  float64
16       Landsize        1448  float64
17          Price        2204  float64
18      Lattitude        6503  float64
19     Longtitude        7063  float64
20    Coordinates       13097   object
21        Address       13378   object
22          index       13580    int64

In [8]:
melb_df['Regionname'].cat.categories

AttributeError: Can only use .cat accessor with a 'category' dtype